### ISSUE TITLE
Problem when connecting to a server configured with password auth

### ISSUE THREAD

**Issue by renatocan** [mo3rfan/syncplayer#17]
Hi Irfan,

Thanks for the project!

I'm trying to setup a personal Syncplay server and I'm getting an error message when using a password on the server and trying to connect with Syncplayer on Android. The server says "Password required".

I don't know much about Android development but I suspect the problem is in line 321 of the file `MediaService.java`:

`mSyncPlayClient = new syncPlayClient(username, room, this.server, null, mSyncPlayClientInterface);`

I think the app is passing `null` as the password. If I'm not wrong, the value to be passed should be `passwd`.

[]'s

Renato.

**Comment by mo3rfan** [comment]
Thanks you're right and sorry for the late fix.
