### ISSUE TITLE
External Media Player

### ISSUE THREAD

**Issue by RaXorX** [mo3rfan/syncplayer#19]
* Version number of app: 1.7.1
* Android OS version: 10

Feature request: Support for playback via external media players.

Hard-coded Subtitles don't show up within the in-built player. This might be a limitation to the player itself and of course, the point of the project might not be to build a good player. Hence, the support for external players might be a better alternative.

**Comment by mo3rfan** [comment]
External media players are the ideal solution but sadly I don't see a way to control the external players and also get the player states.

**Comment by RaXorX** [comment]
Hmm I see, yeah syncplayer might just end up being a background service and that will only arise problems. Same could be said about the external player. Well, what player are you using internally? Is it exo player?

**Comment by mo3rfan** [comment]
Exoplayer, yeah.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
